### ISSUE TITLE
Question: FUOC

### ISSUE THREAD

**Issue by Altrum** [gijsbotje/lef-groningen#1]
Hi, I saw you asked the question here: https://stackoverflow.com/questions/59848992/gatsby-material-ui-fouc-on-page-load about FUOC and it looks like you've fixed it. I was wondering how you did so?

Thanks,
Robert

**Comment by Altrum** [comment]
I ended up figuring out an alternative by using https://github.com/artsy/fresnel.

I'll close this issue

**Comment by gijsbotje** [comment]
@Altrum i seriously have no clue how i fixed it :D didn't even know it was fixed until you notified me, thanks for that
